### ISSUE TITLE
Question: Zen pinbal FX tables

### ISSUE THREAD

**Issue by MikedaSpike** [Fraesh/vps-db#17]
It's not an issue, but a question.
I see that zen pinball FX tables are listed in the json file.
Mostly the tables that are on vpx as well, but also a few "zen only" tables.
But I don't see all the released tables.
Any change that the json file will be updated to contain all the records (and will be updated in the future?)

**Comment by VirtualPinballSpreadsheet** [comment]
Hi there,
Yes, the remaining Pinball FX tables Will be added. I kind of forgot about them. Good thing you mentioned it. :)

I'm adding them as we speak. It will take a while though as I'm including the designer(s), finding and adding a playfield images and all other available information as well.

**Comment by MikedaSpike** [comment]
Awesome ! thanks for that.
Are you also going to put the FX table ID in it, so we can link it to the table from a front end ?

**Comment by VirtualPinballSpreadsheet** [comment]
As promised, I've just added all 108 current tables with all information i could find on various websites including the FX table ID (table xxx).

Here's the original message I just posted on Discord and Facebook:

"For fans of Pinball FX; as of today all (108 current) Pinball FX tables have been added to VPS.
I've tried to add as much information as i could find from Steam, Wiki and PinballFX's own pages, so most fields are filled in.
This also includes the GameFileNames (Table xxx) to use them with a frontend. You can find these in both a special field and in the 'Comment' field.

Sadly i can't test these myself, since i don't own the program, but let me know in the comments if it works. 

Note:
If you want to make a quick PuPlookup file with only the Pinball FX tables, Select 'FX' under 'Features' and it will only export those selected tables.
See the accompanied image."

**Comment by MikedaSpike** [comment]
Thanks, I really appreciate it.
I will check if all data is correct and if I can use it with PinballX.
Again: big thanks !

EDIT: Looked a bit, and I can see all the info ! Thanks you !

**Comment by MikedaSpike** [comment]
Not sure, but think I found 1 small issue.
Table Thor has 2 entries for "fx" , but one should be "fx3" (as 1 of the entries has gamefilename from fx3)
But for the rest of the tables, all looks good. I

**Comment by VirtualPinballSpreadsheet** [comment]
> Not sure, but think I found 1 small issue. Table Thor has 2 entries for "fx" , but one should be "fx3" (as 1 of the entries has gamefilename from fx3) But for the rest of the tables, all looks good. I

Thank you for the heads-up @MikedaSpike . It should be fixed now. :)

**Comment by MikedaSpike** [comment]
you can close this issue (dind't check the last, but I believe you)
